error: Don't Box<> the error implementation
This makes the error objects a bit larger (probably
pointer-sized-plus-discriminator vs. pointer-only) but avoids the heap
allocation; note that the error type is already sized without a box
because io::Error boxes its more complex custom variant data.